# templates/secret.yaml

{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  apiKey: {{ .Values.secret.apiKey | b64enc | quote }}
{{- end }}